
== Preface

This is the reference manual of *MoonTypes*, a library that provides means
to define **C-like structured types** in Lua.
footnote:[
This manual is written in
http://www.methods.co.nz/asciidoc/[AsciiDoc], rendered with
http://asciidoctor.org/[AsciiDoctor] and a CSS from the
https://github.com/asciidoctor/asciidoctor-stylesheet-factory[AsciiDoctor Stylesheet Factory].]

It is assumed that the reader is familiar with the Lua programming language.

=== Getting and installing

MoonTypes requires *http://www.lua.org[Lua]* version 5.3 or greater, and
*http://www.inf.puc-rio.br/~roberto/lpeg/[LPeg]*.

For installation intructions, refer to the README file in the 
https://github.com/stetre/moontypes[*MoonTypes official repository*]
on GitHub.

=== Module organization

The MoonTypes module is loaded using Lua's 
http://www.lua.org/manual/5.3/manual.html#pdf-require[require]() and
returns a table containing the functions it provides 
(as usual with Lua modules). This manual assumes that such
table is named *types*, i.e. that it is loaded with:

[source,lua,indent=1]
----
types = require("moontypes")
----

but nothing forbids the use of a different name.

=== Examples

Complete examples can be found in the *examples/* directory of the release package.

=== License

MoonTypes is released under the *MIT/X11 license* (same as
http://www.lua.org/license.html[Lua], and with the same only requirement to give proper
credits to the original author). 
The copyright notice is in the LICENSE file in the base directory
of the https://github.com/stetre/moontypes[official repository] on GitHub.

[[see-also]]
=== See also

MoonTypes is part of https://github.com/stetre/moonlibs[MoonLibs], a collection of 
Lua libraries for graphics and audio programming.

